#!/bin/sh -e
FOLDER_NAME="$1"
echo "Trying to create animation for scene $FOLDER_NAME"

cd $FOLDER_NAME

### HERE CHANGE Views into FocusedViews or Views_NxM is needed 
## e.g. COLOR_FOLDER="FocusedViews_5x5/Color" 
## remember no spaces!
COLOR_FOLDER="Views/Color"
cd $COLOR_FOLDER
ENDING="_animation.gif"
ANIMATION_NAME="$FOLDER_NAME/$COLOR_FOLDER/color$ENDING"
echo "creating $ANIMATION_NAME"
convert -delay 15 -loop 0 *.png $ANIMATION_NAME
echo "created in $PWD"

### HERE CHANGE Views into FocusedViews or Views_NxM is needed 
## e.g. DISPS_FOLDER="FocusedViews_5x5/Disps" 
## remember no spaces!
DISPS_FOLDER="Views/Disps"
cd $FOLDER_NAME
cd $DISPS_FOLDER
ANIMATION_DISP_NAME="$FOLDER_NAME/$DISPS_FOLDER/disp$ENDING"
echo "creating $ANIMATION_DISP_NAME"
convert -delay 15 -loop 0 *.png $ANIMATION_DISP_NAME
echo "created in $PWD"

